/**
 * @file Integration tests for ASCII preview with builder-generated fixtures
 *
 * Dedicated PPTX fixture files are generated by the builder and saved to
 * spec/preview-fixtures/. These fixtures serve double duty:
 *   1. Verify that the builder produces valid PPTX (chart/table creation)
 *   2. Verify that the preview command renders rich ASCII art
 *
 * Fixtures persist between runs for manual inspection (e.g. LibreOffice).
 */

import { describe, it, expect, beforeAll } from "bun:test";
import { join } from "node:path";
import { generateAllFixtures } from "../../spec/preview-fixtures/generate";
import { runPreview } from "./preview";

let fixturePaths: ReadonlyMap<string, string>;

beforeAll(async () => {
  fixturePaths = await generateAllFixtures();
});

function fixturePath(name: string): string {
  const p = fixturePaths.get(name);
  if (!p) throw new Error(`Fixture "${name}" not found`);
  return p;
}

describe("preview command - builder fixtures", () => {
  // =========================================================================
  // Table
  // =========================================================================
  describe("table rendering", () => {
    it("renders a builder-created table with headers and rows", async () => {
      const result = await runPreview(fixturePath("table"), 1, { width: 100 });
      expect(result.success).toBe(true);
      if (!result.success) return;

      const ascii = result.data.slides[0]!.ascii;
      // Table grid structure
      expect(ascii).toContain("┌");
      expect(ascii).toContain("┘");
      // Cell content
      expect(ascii).toContain("Product");
      expect(ascii).toContain("Price");
      expect(ascii).toContain("Widget");
      expect(ascii).toContain("Gadget");
    });

    it("renders a single-row table (headers only)", async () => {
      const result = await runPreview(fixturePath("table-headers-only"), 1, { width: 80 });
      expect(result.success).toBe(true);
      if (!result.success) return;

      const ascii = result.data.slides[0]!.ascii;
      expect(ascii).toContain("A");
      expect(ascii).toContain("B");
      expect(ascii).toContain("C");
    });
  });

  // =========================================================================
  // Charts
  // =========================================================================
  describe("chart rendering", () => {
    it("renders a bar chart with categories and bar visualization", async () => {
      const result = await runPreview(fixturePath("bar-chart"), 1, { width: 100 });
      expect(result.success).toBe(true);
      if (!result.success) return;

      const ascii = result.data.slides[0]!.ascii;
      expect(ascii).toContain("Q1");
      expect(ascii).toContain("Q2");
      expect(ascii).toContain("Q3");
      expect(ascii).toContain("Q4");
      // Bar visualization
      expect(ascii).toContain("█");
    });

    it("renders a pie chart with percentage distribution", async () => {
      const result = await runPreview(fixturePath("pie-chart"), 1, { width: 100 });
      expect(result.success).toBe(true);
      if (!result.success) return;

      const ascii = result.data.slides[0]!.ascii;
      expect(ascii).toContain("Alpha");
      expect(ascii).toContain("Beta");
      expect(ascii).toContain("Gamma");
      // Pie chart shows percentages
      expect(ascii).toMatch(/\d+\.\d+%/);
    });

    it("renders a line chart with axis lines", async () => {
      const result = await runPreview(fixturePath("line-chart"), 1, { width: 100 });
      expect(result.success).toBe(true);
      if (!result.success) return;

      const ascii = result.data.slides[0]!.ascii;
      expect(ascii).toContain("Jan");
      // Line chart axis characters
      expect(ascii).toContain("│");
      expect(ascii).toContain("─");
    });

    it("renders a multi-series bar chart", async () => {
      const result = await runPreview(fixturePath("multi-series-bar"), 1, { width: 100 });
      expect(result.success).toBe(true);
      if (!result.success) return;

      const ascii = result.data.slides[0]!.ascii;
      expect(ascii).toContain("East");
      expect(ascii).toContain("West");
      expect(ascii).toContain("North");
    });
  });

  // =========================================================================
  // Mixed content (chart + table on same slide)
  // =========================================================================
  describe("mixed content", () => {
    it("renders a slide with both a table and a chart", async () => {
      const result = await runPreview(fixturePath("mixed-table-chart"), 1, { width: 120 });
      expect(result.success).toBe(true);
      if (!result.success) return;

      const ascii = result.data.slides[0]!.ascii;
      expect(result.data.slides[0]!.shapeCount).toBeGreaterThanOrEqual(2);
      // Both table and chart content should be present
      expect(ascii).toContain("Metric");
      expect(ascii).toContain("█");
    });
  });

  // =========================================================================
  // Error handling
  // =========================================================================
  describe("error handling", () => {
    it("returns error for nonexistent file", async () => {
      const result = await runPreview("/nonexistent/file.pptx", 1, { width: 80 });
      expect(result.success).toBe(false);
    });

    it("returns error for invalid slide number", async () => {
      const result = await runPreview(fixturePath("table"), 999, { width: 80 });
      expect(result.success).toBe(false);
    });
  });
});
