/**
 * @file @oxen-builder/pptx - PPTX Builder Package
 *
 * This package provides a unified API for building and exporting PPTX files.
 * It consolidates export functionality, slide operations, and element builders
 * into a single cohesive package.
 */

// Export functionality
export {
  exportPptx,
  exportPptxAsBuffer,
  type ExportOptions,
  type ExportResult,
  type ChartUpdate,
  type WorkbookUpdate,
  type LayoutUpdate,
  type MasterUpdate,
  type ThemeUpdate,
  type ExtendedExportOptions,
  updateEmbeddedXlsx,
  syncAllChartEmbeddings,
  listEmbeddedXlsx,
  getChartRelsPath,
  type GetFileContent,
  type SetFileContent,
  type UpdateEmbeddedXlsxOptions,
} from "./export";

// Slide operations
export {
  applySlideOperations,
  type SlideAddSpec,
  type SlideRemoveSpec,
  type SlideReorderSpec,
  type SlideDuplicateSpec,
  type SlideOperationsResult,
  type SlideOpsStats,
  type SlideOperationsOptions,
  addSlide,
  removeSlide,
  reorderSlide,
  duplicateSlide,
  type SlideAddResult,
  type SlideRemoveResult,
  type SlideReorderResult,
  type SlideDuplicateResult,
  generateSlideId,
  generateSlideRId,
  addSlideToList,
  removeSlideFromList,
  reorderSlideInList,
} from "./slide-ops";

// Builders
// For fill builders (buildColor, buildFill, buildGradientFill, etc.),
// import directly from @oxen-builder/drawing-ml/fill
// For line builders (buildLine, buildLineEnd, buildLineFromSpec),
// import directly from @oxen-builder/drawing-ml/line
// For effects builders (buildEffects, buildBevel, buildShape3d),
// import directly from @oxen-builder/drawing-ml/effect
// For text builders (buildTextBody, buildParagraph, buildTextRun, collectHyperlinks, HyperlinkInfo),
// import directly from @oxen-builder/drawing-ml/text
export {
  generateShapeId,
  setChildren,
  PRESET_MAP,
  buildBlipEffectsFromSpec,
  buildCustomGeometryFromSpec,
  buildMediaReferenceFromSpec,
  detectEmbeddedMediaType,
  applyBackground,
  applyImageBackground,
  isImageBackground,
  // Slide utilities
  getShapeId,
  getExistingShapeIds,
  applyBackgroundSpec,
  // Slide processor
  processSlideElements,
  type SlideModInput,
  type SlideProcessContext,
  type SlideProcessResult,
  applyAnimations,
  type ApplyAnimationsResult,
  applyComments,
  applyNotes,
  applySlideTransition,
  isTransitionType,
  applyThemeEditsToPackage,
  applyThemeEditsToThemeXml,
  applyChartUpdates,
  addChartsToSlide,
  applySmartArtUpdates,
  applyTableUpdates,
  type ApplyTableUpdatesResult,
  type BuildContext,
  type BuildResult,
  type SyncBuilder,
  type AsyncBuilder,
  shapeBuilder,
  imageBuilder,
  connectorBuilder,
  groupBuilder,
  tableBuilder,
  addElementsSync,
  addElementsAsync,
  type AddElementsSyncOptions,
  type AddElementsAsyncOptions,
} from "./builders";

// Types
// NOTE: Common types (Color, Fill, Line, Effects, Text, 3D) should be imported directly from @oxen-builder/drawing-ml
// PPTX-specific types are exported below
export {
  type PlaceholderSpec,
  type ShapeSpec,
  type CustomGeometrySpec,
  type GeometryPathFillMode,
  type GeometryPathSpec,
  type MoveToSpec,
  type LineToSpec,
  type ArcToSpec,
  type QuadBezierToSpec,
  type CubicBezierToSpec,
  type CloseSpec,
  type PathCommandSpec,
  type BlipEffectSpec,
  type ImageSpec,
  type MediaEmbedSpec,
  type ConnectorSpec,
  type GroupSpec,
  type TableCellSpec,
  type TableSpec,
  type TableTextRunSpec,
  type TableParagraphSpec,
  type TableTextBodySpec,
  type TableCellUpdateSpec,
  type TableRowAddSpec,
  type TableColumnAddSpec,
  type TableUpdateSpec,
  type ChartSeriesSpec,
  type ChartDataSpec,
  type ChartTransformSpec,
  type ChartUpdateSpec,
  type ChartOptionsSpec,
  type ChartAddSpec,
  type BackgroundSolidSpec,
  type BackgroundGradientSpec,
  type BackgroundImageSpec,
  type BackgroundFillSpec,
  type SlideTransitionSpec,
  type AnimationClassSpec,
  type AnimationSpec,
  type CommentSpec,
  type NotesSpec,
  type DiagramNodeTextUpdateSpec,
  type DiagramNodeAddSpec,
  type DiagramNodeRemoveSpec,
  type DiagramConnectionSpec,
  type DiagramChangeSpec,
  type SmartArtUpdateSpec,
  type SlideModSpec,
  type BuildSpec,
  type BuildData,
  type ThemeSchemeColorName,
  type ThemeColorSchemeEditSpec,
  type ThemeFontSpec,
  type ThemeFontSchemeEditSpec,
  type ThemeEditSpec,
} from "./types";
